name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Ensure submodules are checked out

    # Step 2: Install build tools (on GitHub Actions runner)
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make

    # Step 3: Compile the C engine
    - name: Build C engine
      run: make

    # Step 4: Configure Git user for commit
    - name: Configure Git user
      run: |
        git config --global user.email "smanahian123@gmail.com"
        git config --global user.name "GitHub Actions"

    # Step 5: Set Heroku Buildpack
    - name: Set Heroku buildpack
      run: |
        heroku buildpacks:set heroku/python --app ${{ secrets.HEROKU_APP_NAME }}

    # Step 6: Link Python dependencies
    - name: Link requirements.txt from lichess-bot directory
      run: |
        cp lichess-bot/requirements.txt .

    # Step 7: Add the compiled binary to the repository
    - name: Add compiled binary
      run: |
        git add -f ssehc
        git commit -m "Include compiled binary for Heroku deployment"

    # Step 8: Create a Procfile dynamically
    - name: Create a Procfile
      run: |
        echo "worker: ./run_lichess_bot.sh" > Procfile

    # Step 9: Deploy to Heroku
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku master --force
