name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    # Install required dependencies
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make

    # Compile the Chess engine
    - name: Build Chess engine
      run: make

    # Prepare deployment files
    - name: Prepare requirements.txt, Procfile and the engine
      run: |
        ln -s lichess-bot/requirements.txt requirements.txt
        echo "worker: ./run_lichess_bot.sh" > Procfile
        git add -f ssehc

    # Deploy to Heroku
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        branch: master
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: smanahian123@gmail.com
        buildpack: heroku/python
