name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install build tools (on GitHub Actions runner)
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make

    # Step 3: Compile the C engine
    - name: Build C engine
      run: make

    # Step 4: Configure Git user for commit
    - name: Configure Git user
      run: |
        git config --global user.email "smanahian123@gmail.com"
        git config --global user.name "GitHub Actions"

    # Step 5: Set Heroku Buildpack
    - name: Set Heroku buildpack
      run: |
        heroku buildpacks:set heroku/python --app ${{ secrets.HEROKU_APP_NAME }}

    # Step 6: Ensure Python dependencies are available by linking requirements.txt
    - name: Link requirements.txt from lichess-bot directory
      run: |
        cp lichess-bot/requirements.txt .

    # Step 7: Add compiled binary to the repository
    - name: Include binary in deployment
      run: |
        git add -f ssehc
        git commit -m "Include compiled binary for Heroku deployment"

    # Step 8: Deploy to Heroku
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: smanahian123@gmail.com
        process_types: |
          worker: ./run_lichess_bot.sh
