name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Ensure submodules are checked out

    # Install required dependencies
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make

    # Compile the C engine
    - name: Build C engine
      run: make

    # Configure Git user for commit
    - name: Configure Git user
      run: |
        echo "machine git.heroku.com login _ token ${HEROKU_API_KEY}" > ~/.netrc

    # Set Heroku Buildpack
    - name: Set Heroku buildpack
      run: |
        heroku buildpacks:set heroku/python --app ${{ secrets.HEROKU_APP_NAME }}

    # Link Python dependencies
    - name: Link requirements.txt from lichess-bot directory
      run: |
        cp lichess-bot/requirements.txt .

    # Configure Git user identity for commits
    - name: Configure Git user
      run: |
        git config --global user.email "smanahian123@gmail.com"
        git config --global user.name "GitHub Actions"

    # Add the compiled binary to the repository
    - name: Add compiled binary
      run: |
        git add -f ssehc
        git commit -m "Include compiled binary for Heroku deployment"

    # Create a Procfile dynamically
    - name: Create a Procfile
      run: |
        echo "worker: ./run_lichess_bot.sh" > Procfile

    # Deploy to Heroku
    - name: Deploy to Heroku
      run: |
        git push heroku main --force
